### ISSUE TITLE
callout CSS/SCSS files (tip, activity, and exercises)

### ISSUE THREAD

**Issue by chendaniely** [UBC-MDS/DSCI_521_platforms-dsci_book#12]
The built-in quarto tip callout looks uses the code:

```
:::{.callout-tip}
tip text here
:::
```

currently the book uses:

```
::: {.tip}
::::{.tip-header}
Tip
::::
::::{.tip-container}
Tip Text Here
::::
:::
```

This is a big difference in amount of typing and tracking fenced divs `:::`, we should aim to make the syntax simpler and leverage the existing ways to modify callouts: <https://quarto.org/docs/authoring/callouts.html>

For the activities, we have it written as:

```
:::{.activity}
::::{.activity-header}
## Activity 3
::::
::::{.activity-container}
TEXT
::::
:::
```

We should not need to specify the `##` in the activity header since we would end up controlling that in the CSS for that div

**Comment by andytai7** [comment]
This should be resolved
